const mongoose = require('mongoose');

let zonePlcLivedataSchema = mongoose.Schema({
    data_id:{
        type:Number,
        maxLength:111,
        default:null
    },
    plc_slno:{
        type:String,
        maxLength:90,
        default:null
    },
    main_meter_flow:{
        type:String,
        maxLength:90,
        default:null
    },
    main_meter_demand_flow:{
        type:String,
        maxLength:30,
        default:null
    },
    sub_flow_meter_1:{
        type:String,
        maxLength:48,
        default:null
    },
    sub_flow_meter_2:{
        type:String,
        maxLength:48,
        default:null
    },
    sub_flow_meter_3:{
        type:String,
        maxLength:48,
        default:null
    },
    sub_flow_meter_4:{
        type:String,
        maxLength:48,
        default:null
    },
    esr_presure:{
        type:String,
        maxLength:90,
        default:null 
    },
    esr_outlet_presure:{
        type:Number,
        maxLength:90,
        default:null
    },
    esr_level: {
        type:String,
        maxLength:90,
        default:null
    },
    valve_status :{
        type:String,
        maxLength:3,
        default:null
    },
    gene_red_volt:{
        type:String,
        maxLength:21,
        default:null
    },
    gene_yel_volt:{
        type:String,
        maxLength:21,
        default:null
    },
    gene_blu_volt:{
        type:String,
        maxLength:21,
        default:null
    },
    gene_red_current:{
        type:String,
        maxLength:15,
        default:null
    },
    gene_yel_current:{
        type:String,
        maxLength:15,
        default:null
    },
    gene_blu_current:{
        type:String,
        maxLength:15,
        default:null
    },
    main_red_volt:{
        type:String,
        maxLength:21,
        default:null 
    },
    main_yel_volt:{
        type:Number,
        maxLength:21,
        default:null
    },
    main_blu_volt: {
        type:String,
        maxLength:21,
        default:null
    },
    main_red_current:{
        type:String,
        maxLength:15,
        default:null
    },
    main_yel_curren:{
        type:String,
        maxLength:15,
        default:null
    },
    main_blu_current:{
        type:String,
        maxLength:15,
        default:null
    },
    generator_fule_level:{
        type:String,
        maxLength:24,
        default:null
    },
    date_time:{
        type:String,
        required:true
    },time:{
        type:String,
        default:null
    }
})
module.exports = mongoose.model('ZonePlcLivedata',zonePlcLivedataSchema);